### PR TITLE
Losslessly optimise file size of mod assets

### PR DESCRIPTION
**Pull request by NeRdTheNed**
This PR focuses on two areas for optimisation: .json files and .png files. I've attempted to document each individual optimisation by committing them separately, with messages explaining any changes that might be confusing or unclear.

Changes:
- All .png files have had their file size reduced drastically through a combination of lossless re-compression (i.e. the image data has not been modified, only the compression has been improved) and having all metadata removed (e.g. tags containing the program used to make an image etc).
- .json block models now use a "template" block model, which is just the model for a generic "iron chest" block (as all models are exactly the same), replacing the model each file included. This means that each individual model .json file uses this "template" model, and supplies the textures for the given chest.
- All recipes referring to all glass types (e.g. the crystal chest recipe, chest upgrades etc) now use a "sand" tag, replacing the previous list of sand each file included. This sand tag contains each type of sand previously listed.
- When the mod is built, each .json file is minified during the process of copying it into the built .jar file. This results in a file size reduction for every .json file, and does not affect the "source" file, which is left intact. This also has the bonus addition of validating each .json file when building the mod, preventing broken .json files from accidentally being unnoticed.
- Minor additional cleanups have been performed to the fabric.mod.json file, and the unused ironchest.mixins.json file has been deleted.

None of these optimisations cause any visual differences, or semantic differences to the image data, models or recipes (all mod content is exactly the same). After building the mod, this results in a file size reduction of around 70kb, bringing the built .jar file size down from around 452kb to around 382kb.

### CODE REVIEW

**Comment by NeRdTheNed** [comment]
Hey @TechnoVisionDev, sorry to ping you! I just remembered that GitHub doesn’t automatically notify people when a pull request is made to a repository, hence the ping. This PR is ready to merge, and the documentation for all changes should hopefully be fairly understandable!

**Comment by NeRdTheNed** [comment]
Just found some more potential for .png optimisations! After I finish those, I'll change the PR back to ready to merge.

**Comment by NeRdTheNed** [comment]
@TechnoVisionDev sorry to ping you twice! This PR should now be completely ready to merge!

**Comment by TechnoVisionDev** [comment]
Great work, this will greatly reduce the jar size and make things much more readable!

**Pull request merged**
